-- 운영 적용 전 staging에서 반드시 schema/row-count/RPC smoke test를 수행한다.
-- 이 migration은 기존 테이블·컬럼·RPC를 삭제하거나 이름을 바꾸지 않고 additive하게 확장한다.

create table if not exists public.companies (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint companies_name_not_blank check (nullif(btrim(name), '') is not null),
  constraint companies_name_unique unique (name)
);

create table if not exists public.permission_definitions (
  id bigint generated by default as identity primary key,
  code text not null,
  label text not null,
  resource text not null,
  action text not null,
  default_data_scope text not null default 'personal'
    check (default_data_scope in ('personal', 'company', 'all')),
  created_at timestamptz not null default now(),
  constraint permission_definitions_code_unique unique (code)
);

create table if not exists public.permission_bindings (
  id bigint generated by default as identity primary key,
  subject_type text not null
    check (subject_type in ('global', 'company', 'role', 'admin')),
  subject_id text,
  permission_code text not null references public.permission_definitions(code),
  effect text not null check (effect in ('allow', 'deny')),
  data_scope text not null default 'personal'
    check (data_scope in ('personal', 'company', 'all')),
  priority integer not null default 0,
  created_at timestamptz not null default now(),
  constraint permission_bindings_subject_id_check check (
    (subject_type = 'global' and subject_id is null)
    or (subject_type <> 'global' and nullif(btrim(subject_id), '') is not null)
  ),
  constraint permission_bindings_unique unique (
    subject_type,
    subject_id,
    permission_code,
    effect,
    data_scope
  )
);

create index if not exists permission_bindings_subject_idx
  on public.permission_bindings (subject_type, subject_id, permission_code);

create index if not exists permission_bindings_permission_idx
  on public.permission_bindings (permission_code, effect);

create table if not exists public.settings_definitions (
  key text primary key,
  label text not null,
  value_type text not null
    check (value_type in ('integer', 'enum', 'string', 'boolean', 'json')),
  unit text,
  min_value numeric,
  max_value numeric,
  default_value jsonb,
  nullable boolean not null default false,
  allowed_values text[] not null default '{}'::text[],
  allowed_scopes text[] not null default array['admin']::text[],
  applicable_roles text[] not null default array['developer', 'company_admin', 'employee']::text[],
  created_at timestamptz not null default now(),
  constraint settings_definitions_range_check check (
    min_value is null or max_value is null or min_value <= max_value
  )
);

create table if not exists public.settings_values (
  id bigint generated by default as identity primary key,
  setting_key text not null references public.settings_definitions(key),
  scope_type text not null check (scope_type in ('company', 'role', 'admin')),
  scope_id text not null,
  value jsonb,
  updated_by text references public.admins(login_id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint settings_values_scope_id_not_blank check (nullif(btrim(scope_id), '') is not null),
  constraint settings_values_unique unique (setting_key, scope_type, scope_id)
);

create index if not exists settings_values_scope_idx
  on public.settings_values (scope_type, scope_id, setting_key);

create table if not exists public.admin_change_audits (
  id bigint generated by default as identity primary key,
  actor_admin_id text references public.admins(login_id),
  target_admin_id text references public.admins(login_id),
  company_id bigint references public.companies(id),
  event_type text not null,
  before_value jsonb,
  after_value jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_change_audits_company_created_idx
  on public.admin_change_audits (company_id, created_at desc);

create index if not exists admin_change_audits_actor_created_idx
  on public.admin_change_audits (actor_admin_id, created_at desc);

alter table public.admins
  add column if not exists company_id bigint,
  add column if not exists role text,
  add column if not exists is_active boolean not null default true,
  add column if not exists include_company_data_include boolean,
  add column if not exists can_verify_deposit boolean;

alter table public.settings_definitions
  add column if not exists allowed_values text[] not null default '{}'::text[];

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'admins_company_id_fkey'
      and conrelid = 'public.admins'::regclass
  ) then
    alter table public.admins
      add constraint admins_company_id_fkey
      foreign key (company_id) references public.companies(id);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'admins_role_check'
      and conrelid = 'public.admins'::regclass
  ) then
    alter table public.admins
      add constraint admins_role_check
      check (role is null or role in ('developer', 'company_admin', 'employee'));
  end if;
end;
$$;

create index if not exists admins_company_role_idx
  on public.admins (company_id, role, login_id);

-- 회사 식별자는 표시용 company 문자열과 분리한다. 같은 migration을 다시 실행해도
-- 기존 회사/계정 연결을 중복 생성하지 않는다.
insert into public.companies (name)
select distinct btrim(company)
from public.admins
where nullif(btrim(company), '') is not null
on conflict (name) do nothing;

update public.admins as admins
set company_id = companies.id
from public.companies as companies
where admins.company_id is null
  and nullif(btrim(admins.company), '') = companies.name;

-- 초기 역할은 사용자가 확정한 현재 계정 구성을 데이터 backfill로만 기록한다.
-- 이후 계정 생성/역할 변경은 외부 운영 절차에서 관리한다.
update public.admins
set role = case
  when login_id = '2sssg' then 'developer'
  when login_id = 'hyejin2054' then 'company_admin'
  when btrim(company) = '테스트커머스' then 'company_admin'
  else 'employee'
end
where role is null;

-- 기존 코드의 계정별 fallback과 동일한 값만 nullable capability 컬럼에
-- backfill한다. 새 권한 binding이 준비되기 전에도 구형 번들의 결과를 보존한다.
update public.admins
set
  include_company_data_include = coalesce(
    include_company_data_include,
    case when login_id = 'hyejin2054' then true else false end
  ),
  can_verify_deposit = coalesce(
    can_verify_deposit,
    case when login_id in ('aram2525', 'kimhanbi77') then false else true end
  );

-- 외부 운영 절차에서 역할/활성 상태를 바꾸더라도 마지막 활성 developer를
-- 실수로 제거하지 않도록 DB 수준에서 보호한다.
create or replace function public.prevent_last_active_developer_change()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_other_developer_count integer;
begin
  if TG_OP = 'DELETE' then
    if old.role <> 'developer' then
      return old;
    end if;
  elsif old.role = 'developer'
    and (new.role is distinct from 'developer' or coalesce(new.is_active, true) = false) then
    null;
  else
    return new;
  end if;

  if old.role = 'developer' then
    select count(*)
    into v_other_developer_count
    from public.admins as admins
    where admins.login_id <> old.login_id
      and admins.role = 'developer'
      and coalesce(admins.is_active, true) = true;

    if v_other_developer_count = 0 then
      raise exception '활성 developer는 최소 1명 이상 유지해야 합니다.' using errcode = '23514';
    end if;
  end if;

  return case when TG_OP = 'DELETE' then old else new end;
end;
$$;

drop trigger if exists admins_prevent_last_active_developer on public.admins;
create trigger admins_prevent_last_active_developer
before delete or update of role, is_active on public.admins
for each row
execute function public.prevent_last_active_developer_change();

revoke all on function public.prevent_last_active_developer_change() from public;
revoke all on function public.prevent_last_active_developer_change() from anon;
revoke all on function public.prevent_last_active_developer_change() from authenticated;

insert into public.permission_definitions (code, label, resource, action, default_data_scope)
values
  ('menu.dashboard', '대시보드 메뉴', 'menu', 'dashboard', 'personal'),
  ('menu.product', '상품 메뉴', 'menu', 'product', 'personal'),
  ('menu.review_receive', '리뷰받기 메뉴', 'menu', 'review_receive', 'personal'),
  ('menu.product_overview', '상품전체보기 메뉴', 'menu', 'product_overview', 'personal'),
  ('menu.export', '내보내기 메뉴', 'menu', 'export', 'personal'),
  ('menu.file_upload', '파일 업로드 메뉴', 'menu', 'file_upload', 'personal'),
  ('menu.bulk_edit', '일괄수정 메뉴', 'menu', 'bulk_edit', 'personal'),
  ('product.read', '상품 조회', 'product', 'read', 'personal'),
  ('product.create', '상품 생성', 'product', 'create', 'personal'),
  ('product.update', '상품 수정', 'product', 'update', 'personal'),
  ('product.delete', '상품 삭제', 'product', 'delete', 'personal'),
  ('product_step.read', '상품 단계 조회', 'product_step', 'read', 'personal'),
  ('product_step.create', '상품 단계 생성', 'product_step', 'create', 'personal'),
  ('product_step.update', '상품 단계 수정', 'product_step', 'update', 'personal'),
  ('product_step.delete', '상품 단계 삭제', 'product_step', 'delete', 'personal'),
  ('application.read', '신청자 조회', 'application', 'read', 'personal'),
  ('application.create', '신청자 생성', 'application', 'create', 'personal'),
  ('application.update', '신청자 수정', 'application', 'update', 'personal'),
  ('application.delete', '신청자 삭제', 'application', 'delete', 'personal'),
  ('application.confirm', '신청자 확정', 'application', 'confirm', 'personal'),
  ('submission.read', '제출 조회', 'submission', 'read', 'personal'),
  ('submission.create', '제출 생성', 'submission', 'create', 'personal'),
  ('submission.update', '제출 수정', 'submission', 'update', 'personal'),
  ('submission.delete', '제출 삭제', 'submission', 'delete', 'personal'),
  ('submission.deposit.verify', '입금 확인', 'submission', 'deposit.verify', 'personal'),
  ('submission.depositor_name.update', '예정 입금자명 수정', 'submission', 'depositor_name.update', 'personal'),
  ('submission.photo.read', '증빙 사진 조회', 'submission', 'photo.read', 'personal'),
  ('submission.photo.upload', '증빙 사진 업로드', 'submission', 'photo.upload', 'personal'),
  ('submission.photo.delete', '증빙 사진 삭제', 'submission', 'photo.delete', 'personal'),
  ('export.execute', '내보내기 실행', 'export', 'execute', 'personal'),
  ('bulk_edit.execute', '일괄수정 실행', 'bulk_edit', 'execute', 'personal'),
  ('admin_member.read', '임직원 조회', 'admin_member', 'read', 'company'),
  ('admin_permission.update', '임직원 권한 변경', 'admin_permission', 'update', 'company'),
  ('company_setting.read', '회사 설정 조회', 'company_setting', 'read', 'company'),
  ('company_setting.update', '회사 설정 변경', 'company_setting', 'update', 'company'),
  ('personal_setting.read', '개인 설정 조회', 'personal_setting', 'read', 'personal'),
  ('personal_setting.update', '개인 설정 변경', 'personal_setting', 'update', 'personal'),
  ('audit.read', '권한 변경 이력 조회', 'audit', 'read', 'all')
on conflict (code) do update set
  label = excluded.label,
  resource = excluded.resource,
  action = excluded.action,
  default_data_scope = excluded.default_data_scope;

-- 관리 화면 자체의 권한은 역할 기본값으로 seed한다. 상품/제출의 기존
-- resource-action 권한은 Phase 0 스냅샷을 확인하기 전까지 임의로 허용하지 않는다.
insert into public.permission_bindings (
  subject_type,
  subject_id,
  permission_code,
  effect,
  data_scope
)
values
  ('role', 'developer', 'admin_member.read', 'allow', 'all'),
  ('role', 'developer', 'admin_permission.update', 'allow', 'all'),
  ('role', 'developer', 'company_setting.read', 'allow', 'all'),
  ('role', 'developer', 'company_setting.update', 'allow', 'all'),
  ('role', 'developer', 'personal_setting.read', 'allow', 'all'),
  ('role', 'developer', 'personal_setting.update', 'allow', 'all'),
  ('role', 'company_admin', 'admin_member.read', 'allow', 'company'),
  ('role', 'company_admin', 'admin_permission.update', 'allow', 'company'),
  ('role', 'company_admin', 'company_setting.read', 'allow', 'company'),
  ('role', 'company_admin', 'company_setting.update', 'allow', 'company'),
  ('role', 'company_admin', 'personal_setting.read', 'allow', 'personal'),
  ('role', 'company_admin', 'personal_setting.update', 'allow', 'personal'),
  ('role', 'employee', 'personal_setting.read', 'allow', 'personal'),
  ('role', 'employee', 'personal_setting.update', 'allow', 'personal')
on conflict (subject_type, subject_id, permission_code, effect, data_scope) do nothing;

insert into public.settings_definitions (
  key,
  label,
  value_type,
  unit,
  min_value,
  max_value,
  default_value,
  nullable,
  allowed_values,
  allowed_scopes,
  applicable_roles
)
values
  ('company_name_trim_length', '예정 입금자명 회사명 자르기', 'integer', 'characters', 0, 100, '0'::jsonb, false, '{}'::text[], array['company']::text[], array['developer', 'company_admin', 'employee']::text[]),
  ('product_fee_deposit_party', '제품비 입금구분 기본값', 'enum', null, null, null, '"self"'::jsonb, false, array['self', 'company']::text[], array['company', 'role', 'admin']::text[], array['developer', 'company_admin', 'employee']::text[]),
  ('review_fee_deposit_party', '리뷰비 입금구분 기본값', 'enum', null, null, null, '"self"'::jsonb, false, array['self', 'company']::text[], array['company', 'role', 'admin']::text[], array['developer', 'company_admin', 'employee']::text[]),
  ('review_fee_default_amount', '리뷰비 기본 금액', 'integer', 'KRW', 0, null, null, true, '{}'::text[], array['company', 'role', 'admin']::text[], array['developer', 'company_admin', 'employee']::text[]),
  ('review_type_default', '리뷰형태 기본값', 'string', null, null, null, null, true, '{}'::text[], array['company', 'role', 'admin']::text[], array['developer', 'company_admin', 'employee']::text[]),
  ('real_shipping_default', '실배송 여부 기본값', 'boolean', null, null, null, null, true, '{}'::text[], array['company', 'role', 'admin']::text[], array['developer', 'company_admin', 'employee']::text[]),
  ('dashboard_period', '대시보드 초기 기간', 'json', null, null, null, null, true, '{}'::text[], array['admin']::text[], array['developer', 'company_admin', 'employee']::text[]),
  ('review_receive_tab', '리뷰받기 초기 탭', 'string', null, null, null, null, true, '{}'::text[], array['admin']::text[], array['developer', 'company_admin', 'employee']::text[]),
  ('review_receive_scope', '리뷰받기 초기 범위', 'string', null, null, null, null, true, '{}'::text[], array['admin']::text[], array['developer', 'company_admin', 'employee']::text[]),
  ('export_columns', '내보내기 컬럼 선택', 'json', null, null, null, null, true, '{}'::text[], array['admin']::text[], array['developer', 'company_admin', 'employee']::text[]),
  ('sidebar_collapsed', '사이드바 접힘 상태', 'boolean', null, null, null, 'false'::jsonb, false, '{}'::text[], array['admin']::text[], array['developer', 'company_admin', 'employee']::text[])
on conflict (key) do update set
  label = excluded.label,
  value_type = excluded.value_type,
  unit = excluded.unit,
  min_value = excluded.min_value,
  max_value = excluded.max_value,
  nullable = excluded.nullable,
  allowed_values = excluded.allowed_values,
  allowed_scopes = excluded.allowed_scopes,
  applicable_roles = excluded.applicable_roles;

-- 기존 개인 메뉴 권한은 새 resolver의 개인 allow binding으로 복사한다.
-- 기존 행은 삭제하지 않으므로 구형 번들의 read path와 rollback을 보존한다.
insert into public.permission_bindings (
  subject_type,
  subject_id,
  permission_code,
  effect,
  data_scope
)
select
  'admin',
  permissions.admin_id,
  case permissions.menu_number
    when 1 then 'menu.dashboard'
    when 2 then 'menu.product'
    when 3 then 'menu.review_receive'
    when 4 then 'menu.product_overview'
    when 5 then 'menu.export'
    when 6 then 'menu.file_upload'
    when 7 then 'menu.bulk_edit'
  end,
  'allow',
  'personal'
from public.admin_menu_permissions as permissions
where permissions.menu_number between 1 and 7
  and not exists (
    select 1
    from public.permission_bindings as existing
    where existing.subject_type = 'admin'
      and existing.subject_id = permissions.admin_id
      and existing.permission_code = case permissions.menu_number
        when 1 then 'menu.dashboard'
        when 2 then 'menu.product'
        when 3 then 'menu.review_receive'
        when 4 then 'menu.product_overview'
        when 5 then 'menu.export'
        when 6 then 'menu.file_upload'
        when 7 then 'menu.bulk_edit'
      end
      and existing.effect = 'allow'
      and existing.data_scope = 'personal'
  );

-- 현재 capability의 예외(aram2525/kimhanbi77)는 새 개인 deny row로 명시한다.
insert into public.permission_bindings (
  subject_type,
  subject_id,
  permission_code,
  effect,
  data_scope
)
select 'admin', blocked.login_id, 'submission.deposit.verify', 'deny', 'personal'
from public.admins as blocked
where blocked.login_id in ('aram2525', 'kimhanbi77')
  and not exists (
    select 1
    from public.permission_bindings as existing
    where existing.subject_type = 'admin'
      and existing.subject_id = blocked.login_id
      and existing.permission_code = 'submission.deposit.verify'
      and existing.effect = 'deny'
  );

-- 다른 계정의 현재 capability는 기존 컬럼/Phase 0 스냅샷을 확인한 뒤 추가한다.
-- 이 migration은 확인되지 않은 resource-action을 임의로 허용하지 않는다.

comment on table public.permission_bindings is
  '회사·역할·개인 권한 부여. 최종 판정은 서버 gateway/RPC에서 수행하며 기존 menu/capability 행을 호환 유지한다.';

comment on table public.settings_values is
  '회사·역할·개인 설정값. 개인 row 삭제 시 상위 회사/역할 기본값을 다시 상속한다.';

-- 새 정규화 테이블은 gateway/RPC 전용이다. restrictive RLS는 인증 주체와
-- 구형 번들 호환을 검증한 뒤 별도 migration에서 활성화한다.
revoke all on table
  public.companies,
  public.permission_definitions,
  public.permission_bindings,
  public.settings_definitions,
  public.settings_values,
  public.admin_change_audits
from anon, authenticated;

grant all on table
  public.companies,
  public.permission_definitions,
  public.permission_bindings,
  public.settings_definitions,
  public.settings_values,
  public.admin_change_audits
to service_role;

-- 새 gateway가 한 번에 읽을 수 있는 호환 bundle이다. 구형 웹 번들은 이 RPC를
-- 호출하지 않으며, 함수 실행 권한도 service_role로 제한한다.
create or replace function public.get_admin_access_bundle(p_admin_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin public.admins%rowtype;
  v_permissions jsonb;
  v_menu_permissions jsonb;
  v_settings jsonb;
begin
  select *
  into v_admin
  from public.admins
  where login_id = p_admin_id
    and coalesce(is_active, true) = true;

  if not found then
    raise exception '관리자 정보를 찾지 못했습니다.' using errcode = '28000';
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', bindings.id,
        'permissionCode', bindings.permission_code,
        'effect', bindings.effect,
        'dataScope', bindings.data_scope,
        'subjectType', bindings.subject_type,
        'subjectId', bindings.subject_id,
        'priority', bindings.priority
      )
      order by bindings.permission_code, bindings.subject_type, bindings.priority
    ),
    '[]'::jsonb
  )
  into v_permissions
  from public.permission_bindings as bindings
  where bindings.subject_type = 'global'
    or (bindings.subject_type = 'company' and bindings.subject_id = v_admin.company_id::text)
    or (bindings.subject_type = 'role' and lower(bindings.subject_id) = lower(v_admin.role))
    or (bindings.subject_type = 'admin' and bindings.subject_id = v_admin.login_id);

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'admin_id', v_admin.login_id,
        'menu_number', case bindings.permission_code
          when 'menu.dashboard' then 1
          when 'menu.product' then 2
          when 'menu.review_receive' then 3
          when 'menu.product_overview' then 4
          when 'menu.export' then 5
          when 'menu.file_upload' then 6
          when 'menu.bulk_edit' then 7
        end,
        'permission_code', bindings.permission_code,
        'effect', bindings.effect,
        'data_scope', bindings.data_scope
      )
      order by case bindings.permission_code
        when 'menu.dashboard' then 1
        when 'menu.product' then 2
        when 'menu.review_receive' then 3
        when 'menu.product_overview' then 4
        when 'menu.export' then 5
        when 'menu.file_upload' then 6
        when 'menu.bulk_edit' then 7
        else 99
      end
    ),
    '[]'::jsonb
  )
  into v_menu_permissions
  from public.permission_bindings as bindings
  where bindings.effect = 'allow'
    and bindings.permission_code in (
      'menu.dashboard',
      'menu.product',
      'menu.review_receive',
      'menu.product_overview',
      'menu.export',
      'menu.file_upload',
      'menu.bulk_edit'
    )
    and (
      bindings.subject_type = 'global'
      or (bindings.subject_type = 'company' and bindings.subject_id = v_admin.company_id::text)
      or (bindings.subject_type = 'role' and lower(bindings.subject_id) = lower(v_admin.role))
      or (bindings.subject_type = 'admin' and bindings.subject_id = v_admin.login_id)
    );

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'key', definitions.key,
        'value', coalesce(resolved.value, definitions.default_value),
        'source', coalesce(resolved.scope_type, 'definition'),
        'hasOverride', resolved.scope_type = 'admin'
      )
      order by definitions.key
    ),
    '[]'::jsonb
  )
  into v_settings
  from public.settings_definitions as definitions
  left join lateral (
    select setting_values.value, setting_values.scope_type
    from public.settings_values as setting_values
    where setting_values.setting_key = definitions.key
      and (
        (setting_values.scope_type = 'company' and setting_values.scope_id = v_admin.company_id::text)
        or (setting_values.scope_type = 'role' and lower(setting_values.scope_id) = lower(v_admin.role))
        or (setting_values.scope_type = 'admin' and setting_values.scope_id = v_admin.login_id)
      )
    order by case setting_values.scope_type when 'company' then 1 when 'role' then 2 when 'admin' then 3 else 0 end desc
    limit 1
  ) as resolved on true;

  return jsonb_build_object(
    'principal', jsonb_build_object(
      'adminId', v_admin.login_id,
      'companyId', v_admin.company_id,
      'role', v_admin.role
    ),
    'profile', jsonb_build_object(
      'loginId', v_admin.login_id,
      'username', v_admin.username,
      'email', v_admin.email,
      'company', v_admin.company,
      'companyId', v_admin.company_id,
      'role', v_admin.role,
      'isActive', coalesce(v_admin.is_active, true)
    ),
    'role', v_admin.role,
    'companyId', v_admin.company_id,
    'capabilities', jsonb_build_object(
      'includeCompanyDataInclude', case
        when v_admin.role = 'developer' then true
        else coalesce(v_admin.include_company_data_include, false)
      end,
      'canVerifyDeposit', coalesce(v_admin.can_verify_deposit, true)
    ),
    'permissions', v_permissions,
    'permissionBindings', v_permissions,
    'menuPermissions', v_menu_permissions,
    'settings', v_settings
  );
end;
$$;

revoke all on function public.get_admin_access_bundle(text) from public;
revoke all on function public.get_admin_access_bundle(text) from anon;
revoke all on function public.get_admin_access_bundle(text) from authenticated;
grant execute on function public.get_admin_access_bundle(text) to service_role;

-- 개발자와 company_admin이 관리할 수 있는 임직원 목록과 개인 권한을
-- 하나의 서버 응답으로 반환한다. 역할·회사 범위는 여기서 다시 확인한다.
create or replace function public.get_admin_members(p_actor_admin_id text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor public.admins%rowtype;
  v_members jsonb;
begin
  select * into v_actor
  from public.admins
  where login_id = p_actor_admin_id
    and coalesce(is_active, true) = true;

  if not found then
    raise exception '관리자 정보를 찾지 못했습니다.' using errcode = '28000';
  end if;

  if v_actor.role not in ('developer', 'company_admin') then
    raise exception '임직원 관리 권한이 없습니다.' using errcode = '42501';
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'loginId', members.login_id,
        'username', members.username,
        'email', members.email,
        'company', members.company,
        'companyId', members.company_id,
        'role', members.role,
        'isActive', coalesce(members.is_active, true),
        'permissions', coalesce(
          (
            select jsonb_agg(
              jsonb_build_object(
                'id', bindings.id,
                'permissionCode', bindings.permission_code,
                'effect', bindings.effect,
                'dataScope', bindings.data_scope,
                'subjectType', bindings.subject_type,
                'subjectId', bindings.subject_id,
                'priority', bindings.priority
              )
              order by bindings.permission_code, bindings.priority
            )
            from public.permission_bindings as bindings
            where bindings.subject_type = 'global'
              or (bindings.subject_type = 'company' and bindings.subject_id = members.company_id::text)
              or (bindings.subject_type = 'role' and lower(bindings.subject_id) = lower(members.role))
              or (bindings.subject_type = 'admin' and bindings.subject_id = members.login_id)
          ),
          '[]'::jsonb
        )
      )
      order by members.company, members.login_id
    ),
    '[]'::jsonb
  )
  into v_members
  from public.admins as members
  where coalesce(members.is_active, true) = true
    and (
      v_actor.role = 'developer'
      or (
        members.role = 'employee'
        and members.company_id = v_actor.company_id
      )
    );

  return v_members;
end;
$$;

revoke all on function public.get_admin_members(text) from public;
revoke all on function public.get_admin_members(text) from anon;
revoke all on function public.get_admin_members(text) from authenticated;
grant execute on function public.get_admin_members(text) to service_role;

-- 개인 권한은 한 계정·권한 코드당 하나의 명시적 override만 유지한다.
-- p_remove=true이면 상위 회사/역할 기본값을 다시 상속한다.
create or replace function public.update_admin_permission(
  p_actor_admin_id text,
  p_target_admin_id text,
  p_permission_code text,
  p_effect text default null,
  p_data_scope text default 'personal',
  p_remove boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor public.admins%rowtype;
  v_target public.admins%rowtype;
  v_definition public.permission_definitions%rowtype;
  v_effect text := lower(nullif(btrim(p_effect), ''));
  v_data_scope text := lower(nullif(btrim(p_data_scope), ''));
  v_previous jsonb;
begin
  select * into v_actor
  from public.admins
  where login_id = p_actor_admin_id
    and coalesce(is_active, true) = true;

  if not found then
    raise exception '관리자 정보를 찾지 못했습니다.' using errcode = '28000';
  end if;

  select * into v_target
  from public.admins
  where login_id = p_target_admin_id
    and coalesce(is_active, true) = true;

  if not found then
    raise exception '대상 임직원을 찾지 못했습니다.' using errcode = '22023';
  end if;

  if v_actor.role <> 'developer'
    and not (
      v_actor.role = 'company_admin'
      and v_target.role = 'employee'
      and v_actor.company_id = v_target.company_id
    ) then
    raise exception '해당 계정의 권한을 변경할 수 없습니다.' using errcode = '42501';
  end if;

  select * into v_definition
  from public.permission_definitions
  where code = p_permission_code;

  if not found then
    raise exception '알 수 없는 권한 코드입니다.' using errcode = '22023';
  end if;

  if p_remove then
    select jsonb_agg(to_jsonb(bindings)) into v_previous
    from public.permission_bindings as bindings
    where bindings.subject_type = 'admin'
      and bindings.subject_id = v_target.login_id
      and bindings.permission_code = v_definition.code;

    delete from public.permission_bindings
    where subject_type = 'admin'
      and subject_id = v_target.login_id
      and permission_code = v_definition.code;

    insert into public.admin_change_audits (
      actor_admin_id,
      target_admin_id,
      company_id,
      event_type,
      before_value,
      after_value,
      metadata
    )
    values (
      v_actor.login_id,
      v_target.login_id,
      v_target.company_id,
      'permission.override.remove',
      v_previous,
      null,
      jsonb_build_object('permissionCode', v_definition.code)
    );

    return jsonb_build_object(
      'targetAdminId', v_target.login_id,
      'permissionCode', v_definition.code,
      'removed', true
    );
  end if;

  if v_effect not in ('allow', 'deny')
    or v_data_scope not in ('personal', 'company', 'all') then
    raise exception '권한 효과 또는 데이터 범위가 올바르지 않습니다.' using errcode = '22023';
  end if;

  select to_jsonb(bindings) into v_previous
  from public.permission_bindings as bindings
  where bindings.subject_type = 'admin'
    and bindings.subject_id = v_target.login_id
    and bindings.permission_code = v_definition.code
  order by bindings.priority desc, bindings.id desc
  limit 1;

  delete from public.permission_bindings
  where subject_type = 'admin'
    and subject_id = v_target.login_id
    and permission_code = v_definition.code;

  insert into public.permission_bindings (
    subject_type,
    subject_id,
    permission_code,
    effect,
    data_scope
  )
  values (
    'admin',
    v_target.login_id,
    v_definition.code,
    v_effect,
    v_data_scope
  );

  insert into public.admin_change_audits (
    actor_admin_id,
    target_admin_id,
    company_id,
    event_type,
    before_value,
    after_value,
    metadata
  )
  values (
    v_actor.login_id,
    v_target.login_id,
    v_target.company_id,
    'permission.override.update',
    v_previous,
    jsonb_build_object(
      'effect', v_effect,
      'dataScope', v_data_scope
    ),
    jsonb_build_object('permissionCode', v_definition.code)
  );

  return jsonb_build_object(
    'targetAdminId', v_target.login_id,
    'permissionCode', v_definition.code,
    'effect', v_effect,
    'dataScope', v_data_scope,
    'removed', false
  );
end;
$$;

revoke all on function public.update_admin_permission(text, text, text, text, text, boolean) from public;
revoke all on function public.update_admin_permission(text, text, text, text, text, boolean) from anon;
revoke all on function public.update_admin_permission(text, text, text, text, text, boolean) from authenticated;
grant execute on function public.update_admin_permission(text, text, text, text, text, boolean) to service_role;

create or replace function public.update_admin_setting(
  p_actor_admin_id text,
  p_setting_key text,
  p_scope_type text,
  p_scope_id text default null,
  p_value jsonb default null,
  p_remove boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor public.admins%rowtype;
  v_definition public.settings_definitions%rowtype;
  v_scope_type text := lower(nullif(btrim(p_scope_type), ''));
  v_scope_id text := nullif(btrim(p_scope_id), '');
  v_previous_value jsonb;
  v_numeric_value numeric;
begin
  select * into v_actor
  from public.admins
  where login_id = p_actor_admin_id
    and coalesce(is_active, true) = true;

  if not found then
    raise exception '관리자 정보를 찾지 못했습니다.' using errcode = '28000';
  end if;

  select * into v_definition
  from public.settings_definitions
  where key = p_setting_key;

  if not found then
    raise exception '알 수 없는 설정 항목입니다.' using errcode = '22023';
  end if;

  if v_scope_type not in ('company', 'role', 'admin') then
    raise exception '설정 저장 범위가 올바르지 않습니다.' using errcode = '22023';
  end if;

  if v_scope_type = 'company' and v_scope_id is null then
    v_scope_id := v_actor.company_id::text;
  elsif v_scope_type = 'role' and v_scope_id is null then
    v_scope_id := v_actor.role;
  elsif v_scope_type = 'admin' and v_scope_id is null then
    v_scope_id := v_actor.login_id;
  end if;

  if v_scope_id is null or not (v_scope_type = any(v_definition.allowed_scopes)) then
    raise exception '이 설정을 해당 범위에 저장할 수 없습니다.' using errcode = '42501';
  end if;

  if v_scope_type = 'company' then
    if v_actor.role not in ('developer', 'company_admin')
      or (v_actor.role = 'company_admin' and v_scope_id <> v_actor.company_id::text) then
      raise exception '회사 설정을 변경할 권한이 없습니다.' using errcode = '42501';
    end if;
  elsif v_scope_type = 'role' and v_actor.role <> 'developer' then
    raise exception '역할 기본값을 변경할 권한이 없습니다.' using errcode = '42501';
  elsif v_scope_type = 'admin'
    and v_actor.role <> 'developer'
    and v_scope_id <> v_actor.login_id then
    raise exception '다른 계정의 개인 설정을 변경할 권한이 없습니다.' using errcode = '42501';
  end if;

  select value into v_previous_value
  from public.settings_values
  where setting_key = v_definition.key
    and scope_type = v_scope_type
    and scope_id = v_scope_id;

  if p_remove then
    delete from public.settings_values
    where setting_key = v_definition.key
      and scope_type = v_scope_type
      and scope_id = v_scope_id;

    insert into public.admin_change_audits (
      actor_admin_id,
      target_admin_id,
      company_id,
      event_type,
      before_value,
      after_value,
      metadata
    )
    values (
      v_actor.login_id,
      case when v_scope_type = 'admin' then v_scope_id else null end,
      v_actor.company_id,
      'setting.override.remove',
      v_previous_value,
      null,
      jsonb_build_object('settingKey', v_definition.key, 'scopeType', v_scope_type, 'scopeId', v_scope_id)
    );

    return jsonb_build_object('key', v_definition.key, 'scopeType', v_scope_type, 'scopeId', v_scope_id, 'removed', true);
  end if;

  if p_value is null or jsonb_typeof(p_value) = 'null' then
    if not v_definition.nullable then
      raise exception '필수 설정값을 비울 수 없습니다.' using errcode = '22023';
    end if;
  elsif v_definition.value_type = 'integer' then
    if jsonb_typeof(p_value) <> 'number' then
      raise exception '정수 설정값이 올바르지 않습니다.' using errcode = '22023';
    end if;
    v_numeric_value := (p_value #>> '{}')::numeric;
    if v_numeric_value <> trunc(v_numeric_value)
      or (v_definition.min_value is not null and v_numeric_value < v_definition.min_value)
      or (v_definition.max_value is not null and v_numeric_value > v_definition.max_value) then
      raise exception '설정값 범위를 벗어났습니다.' using errcode = '22023';
    end if;
  elsif v_definition.value_type = 'enum' then
    if jsonb_typeof(p_value) <> 'string'
      or not ((p_value #>> '{}') = any(v_definition.allowed_values)) then
      raise exception '허용되지 않은 선택값입니다.' using errcode = '22023';
    end if;
  elsif v_definition.value_type = 'boolean' and jsonb_typeof(p_value) <> 'boolean' then
    raise exception 'boolean 설정값이 올바르지 않습니다.' using errcode = '22023';
  elsif v_definition.value_type = 'string' and jsonb_typeof(p_value) <> 'string' then
    raise exception '문자열 설정값이 올바르지 않습니다.' using errcode = '22023';
  end if;

  insert into public.settings_values (
    setting_key,
    scope_type,
    scope_id,
    value,
    updated_by
  )
  values (
    v_definition.key,
    v_scope_type,
    v_scope_id,
    p_value,
    v_actor.login_id
  )
  on conflict (setting_key, scope_type, scope_id)
  do update set
    value = excluded.value,
    updated_by = excluded.updated_by,
    updated_at = now();

  insert into public.admin_change_audits (
    actor_admin_id,
    target_admin_id,
    company_id,
    event_type,
    before_value,
    after_value,
    metadata
  )
  values (
    v_actor.login_id,
    case when v_scope_type = 'admin' then v_scope_id else null end,
    v_actor.company_id,
    'setting.update',
    v_previous_value,
    p_value,
    jsonb_build_object('settingKey', v_definition.key, 'scopeType', v_scope_type, 'scopeId', v_scope_id)
  );

  return jsonb_build_object(
    'key', v_definition.key,
    'scopeType', v_scope_type,
    'scopeId', v_scope_id,
    'value', p_value,
    'removed', false
  );
end;
$$;

revoke all on function public.update_admin_setting(text, text, text, text, jsonb, boolean) from public;
revoke all on function public.update_admin_setting(text, text, text, text, jsonb, boolean) from anon;
revoke all on function public.update_admin_setting(text, text, text, text, jsonb, boolean) from authenticated;
grant execute on function public.update_admin_setting(text, text, text, text, jsonb, boolean) to service_role;

create or replace function public.update_admin_profile(
  p_actor_admin_id text,
  p_payload jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_admin public.admins%rowtype;
begin
  select * into v_admin
  from public.admins
  where login_id = p_actor_admin_id
    and coalesce(is_active, true) = true;

  if not found then
    raise exception '관리자 정보를 찾지 못했습니다.' using errcode = '28000';
  end if;

  update public.admins
  set
    username = case when p_payload ? 'username' then nullif(btrim(p_payload ->> 'username'), '') else username end,
    phone_number = case when p_payload ? 'phone_number' then nullif(btrim(p_payload ->> 'phone_number'), '') else phone_number end,
    email = case when p_payload ? 'email' then nullif(btrim(p_payload ->> 'email'), '') else email end,
    password = case when p_payload ? 'password' then p_payload ->> 'password' else password end
  where login_id = v_admin.login_id;

  select * into v_admin from public.admins where login_id = p_actor_admin_id;

  return jsonb_build_object(
    'loginId', v_admin.login_id,
    'username', v_admin.username,
    'phone_number', v_admin.phone_number,
    'email', v_admin.email,
    'company', v_admin.company,
    'companyId', v_admin.company_id,
    'role', v_admin.role
  );
end;
$$;

revoke all on function public.update_admin_profile(text, jsonb) from public;
revoke all on function public.update_admin_profile(text, jsonb) from anon;
revoke all on function public.update_admin_profile(text, jsonb) from authenticated;
grant execute on function public.update_admin_profile(text, jsonb) to service_role;

notify pgrst, 'reload schema';
